sudo:       required
language:   generic
services:   docker

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # also it here
- tlmgr install xcolor
- make

