sudo:       required
language:   generic
services:   docker

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run -it --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/tex:tl-small /repo/.travis/build.sh
