sudo:       required
language:   generic
services:   docker

script:
- docker pull strauman/travis-latexbuild:small # select small texlive scheme
- docker run -it --mount src=/home/jim/texmf/tex/latex/ximeraLatex/,target=/repo,type=bind strauman/tex:tl-small /repo/.travis/build.sh

