module.exports = [
    [],
    ["handout"],
    ["instructornotes"],
    ["noinstructornotes"],
    ["nooutcomes"],
    ["noauthor"],
    ["hints"],
    ["numbers"],
    ["wordchoicegiven"],
    ["newpage"],
    ["space"],
    ["handout","nooutcomes"],
    ["handout","instructornotes"],
    ["handout","hints"],
    ["handout","newpage"],
    ["handout","numbers"],
    ["handout","wordchoicegiven"]
];
